### ISSUE TITLE
Mutable defaults in ParametersConfig dataclass

### ISSUE THREAD

**Issue by jacob-evarts** [allen-cell-animated/cell-abm-pipeline#20]
# Issue
A dataclass has class instances as default arguments for dataclass attributes, resulting in a ValueError. Issue occurs while trying to convert simulated cell data into an image format.

# Recreating the issue
1. System specs: python 3.11.9, centOS 7
2. Cloning the repo
3. Installing dependencies and entering a virtual environment with poetry as specified in the README
4. `poetry run abmpipe convert-arcade-format configs/adhesion.yaml`

Contents of adhesion.yaml:
```yaml
context:
    name: adhesion
    working_location: data/
series:
    name: RELATIVE_ADHESION_MINI
    conditions:
        - key: AA012_AX012_DN012_SA012
parameters:
    name: adhesion
    formats: ["images"]
    images:
        seeds: [0]
        box: [150, 150, 10]
        binary: true
```

# Traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ec2-user/cell-abm-pipeline/src/cell_abm_pipeline/__main__.py", line 44, in main
    module = get_module(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/cell-abm-pipeline/src/cell_abm_pipeline/__main__.py", line 70, in get_module
    module = importlib.import_module(f"..flows.{module_name}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ec2-user/cell-abm-pipeline/src/cell_abm_pipeline/flows/convert_arcade_format.py", line 241, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1232, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1222, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'cell_abm_pipeline.flows.convert_arcade_format.ParametersConfigColorizer'> for field colorizer is not allowed: use default_factory
(cell-abm-pipeline-py3.11) [ec2-user@ip-172-31-62-98 cell-abm-pipeline]$ poetry run abmpipe convert-arcade-format configs/adhesion.yaml
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ec2-user/cell-abm-pipeline/src/cell_abm_pipeline/__main__.py", line 44, in main
    module = get_module(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/cell-abm-pipeline/src/cell_abm_pipeline/__main__.py", line 70, in get_module
    module = importlib.import_module(f"..flows.{module_name}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ec2-user/cell-abm-pipeline/src/cell_abm_pipeline/flows/convert_arcade_format.py", line 241, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1232, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1222, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'cell_abm_pipeline.flows.convert_arcade_format.ParametersConfigColorizer'> for field colorizer is not allowed: use default_factory

**Comment by jacob-evarts** [comment]
No access to PR, but this update in convert_arcade_format.py lines 231-254 fixes the issue:

```python
@dataclass
class ParametersConfig:
    """Parameter configuration for convert ARCADE format flow."""

    formats: list[str] = field(default_factory=lambda: FORMATS)
    """List of convert formats."""

    colorizer: ParametersConfigColorizer = field(default_factory=ParametersConfigColorizer)
    """Parameters for colorizer subflow."""

    images: ParametersConfigImages = field(default_factory=ParametersConfigImages)
    """Parameters for images subflow."""

    meshes: ParametersConfigMeshes = field(default_factory=ParametersConfigMeshes)
    """Parameters for meshes subflow."""

    projections: ParametersConfigProjections = field(default_factory=ParametersConfigProjections)
    """Parameters for projections subflow."""

    simularium_shapes: ParametersConfigSimulariumShapes = field(default_factory=ParametersConfigSimulariumShapes)
    """Parameters for simularium shapes subflow."""

    simularium_objects: ParametersConfigSimulariumObjects = field(default_factory=ParametersConfigSimulariumObjects)
    """Parameters for simularium objects subflow."""
```


Old code for reference:
```python
@dataclass
class ParametersConfig:
    """Parameter configuration for convert ARCADE format flow."""

    formats: list[str] = field(default_factory=lambda: FORMATS)
    """List of convert formats."""

    colorizer: ParametersConfigColorizer = ParametersConfigColorizer()
    """Parameters for colorizer subflow."""

    images: ParametersConfigImages = ParametersConfigImages()
    """Parameters for images subflow."""

    meshes: ParametersConfigMeshes = ParametersConfigMeshes()
    """Parameters for meshes subflow."""

    projections: ParametersConfigProjections = ParametersConfigProjections()
    """Parameters for projections subflow."""

    simularium_shapes: ParametersConfigSimulariumShapes = ParametersConfigSimulariumShapes()
    """Parameters for simularium shapes subflow."""

    simularium_objects: ParametersConfigSimulariumObjects = ParametersConfigSimulariumObjects()
    """Parameters for simularium objects subflow."""
```

If there is a reason to not have these inits in factories then disregard this, but the [dataclass docs](https://docs.python.org/3/library/dataclasses.html#mutable-default-values) seem to encourage the factories.

It is also possible there are more mutable defaults in dataclasses in the code, I have not done a thorough check but this was the only one that was giving me issue.

**Comment by jessicasyu** [comment]
Thanks @jacob-evarts! I was unable to reproduce with 3.10, so I wonder if it's a 3.11 thing? 

Out of curiosity, does wrapping `framespec` with a `field` change anything?

```python
frame_spec: tuple[int, int, int] = field(default_factory=lambda: (0, 1153, 1152))
```

Regardless, the change you suggested looks good to me (and consistent with the docs). I believe you can fork the repo and PR from there, if you want? Otherwise, I'm happy to make the change.

I think there are probably a couple other cases floating around. If you have time, I'd appreciate the check. Otherwise, maybe create a new issue to track it?

**Comment by jacob-evarts** [comment]
Great, I can do that! @jessicasyu!

**Comment by jacob-evarts** [comment]
> Out of curiosity, does wrapping `framespec` with a `field` change anything?
> 
> ```python
> frame_spec: tuple[int, int, int] = field(default_factory=lambda: (0, 1153, 1152))
> ```

Doesn't seem to make a difference! I guess since default attributes are shared between dataclass instances, any changes to a mutable attribute would be reflected across all instances, which of course isn't a problem for this `set`! Maybe just negligibly more memory efficient to leave immutable types out of factories.
